"""Initial migration

Revision ID: 8c2944992517
Revises: 
Create Date: 2025-02-15 13:15:47.215994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2944992517'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TickerPrice',
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=True),
    sa.Column('Volume', sa.Integer(), nullable=True),
    sa.Column('StockSplits', sa.Integer(), nullable=True),
    sa.Column('Type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker', 'Date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TickerPrice')
    # ### end Alembic commands ###
